apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    metadata:
      labels:
        app: taskflow-frontend
    spec:
      containers:
      - name: frontend
        image: 362324939829.dkr.ecr.us-east-1.amazonaws.com/taskflow-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: taskflow-frontend
spec:
  type: LoadBalancer
  selector:
    app: taskflow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
