apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-worker
  template:
    metadata:
      labels:
        app: taskflow-worker
    spec:
      containers:
      - name: worker
        image: 362324939829.dkr.ecr.us-east-1.amazonaws.com/taskflow-worker:latest
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/taskflow"
        - name: SQS_QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/362324939829/taskflow-notifications-dev"
        - name: AWS_REGION
          value: "us-east-1"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          exec:
            command: ["pgrep", "node"]
          initialDelaySeconds: 30
