apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend
  namespace: taskflow
spec:
  type: ClusterIP
  selector:
    app: taskflow-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
