apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: taskflow
images:
  - name: BACKEND_IMAGE
    newName: 362324939829.dkr.ecr.us-east-1.amazonaws.com/taskflow-backend
    newTag: latest
  - name: FRONTEND_IMAGE
    newName: 362324939829.dkr.ecr.us-east-1.amazonaws.com/taskflow-frontend
    newTag: latest
  - name: WORKER_IMAGE
    newName: 362324939829.dkr.ecr.us-east-1.amazonaws.com/taskflow-worker
    newTag: latest
