name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if the CI pipeline was completely successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        service: [frontend, backend, worker]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy to EKS & Verify
        env:
          # OUR CRITICAL FIX: Give kubectl its eyes
          KUBECONFIG: /home/runner/.kube/config
        run: |
          # 1. Authenticate to cluster
          aws eks update-kubeconfig --name taskflow-dev --region us-east-1
          
          # 2. Force context (Fixes localhost:8080 bug)
          kubectl config use-context arn:aws:eks:us-east-1:657577038059:cluster/taskflow-dev
          
          # 3. Deploy new image
          echo "Deploying ${{ matrix.service }}..."
          kubectl set image deployment/taskflow-${{ matrix.service }} \
            ${{ matrix.service }}=${{ steps.login-ecr.outputs.registry }}/taskflow-${{ matrix.service }}:${{ github.sha }} \
            -n taskflow
            
          # 4. Wait for rollout (Timeout after 3 minutes)
          kubectl rollout status deployment/taskflow-${{ matrix.service }} -n taskflow --timeout=3m

      # PFE REQUIREMENT: Automated Rollback
      - name: Rollback on Failure
        if: failure()
        env:
          KUBECONFIG: /home/runner/.kube/config
        run: |
          echo "Deployment failed. Initiating automatic rollback for ${{ matrix.service }}..."
          aws eks update-kubeconfig --name taskflow-dev --region us-east-1
          kubectl config use-context arn:aws:eks:us-east-1:657577038059:cluster/taskflow-dev
          
          kubectl rollout undo deployment/taskflow-${{ matrix.service }} -n taskflow
          kubectl rollout status deployment/taskflow-${{ matrix.service }} -n taskflow