name: Deploy Frontend

on:
  push:
    paths: ['frontend/**']
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to ECR
        run: |
          cd frontend
          echo "VITE_API_URL=http://a8b699a5be70a47fc93ae874a090787f-1944154350.us-east-1.elb.amazonaws.com" > .env
          echo "VITE_API_URL=http://a8b699a5be70a47fc93ae874a090787f-1944154350.us-east-1.elb.amazonaws.com" > .env.production

          docker build -t ${{ steps.login-ecr.outputs.registry }}/taskflow-frontend:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/taskflow-frontend:${{ github.sha }}

      - name: Deploy to EKS
        env:
          KUBECONFIG: /home/runner/.kube/config
        run: |
          aws eks update-kubeconfig --name taskflow-dev --region us-east-1
          kubectl config use-context arn:aws:eks:us-east-1:657577038059:cluster/taskflow-dev
          
          # This updates the image to the new version we just pushed
          kubectl set image deployment/taskflow-frontend frontend=${{ steps.login-ecr.outputs.registry }}/taskflow-frontend:${{ github.sha }} -n taskflow
          kubectl rollout status deployment/taskflow-frontend -n taskflow